### ISSUE TITLE
Reconciliation of object.h

### ISSUE THREAD

**Issue by carloa21** [Nomenokes/cs4500as01#3]
Hello,

In order to have my team's object.h file reconcile between all 3 specs, please consider having the method signatures match what's found on [Piazza.](https://piazza.com/class/k51bluky59n2jr?cid=166)

That is:
virtual bool equals(Object* other)
virtual size_t hash() 

Thanks!

**Comment by spencerlachance** [comment]
@carloa21 Your Piazza link is taking me to the professors' utility classes which has a bunch more methods than `equals` and `hash`. Did you mean to link to this [post](https://piazza.com/class/k51bluky59n2jr?cid=345)?

Also, could string.h be reconciled as well? @Nomenokes

**Comment by carloa21** [comment]
I meant that @Nomenokes would just change the signatures of `equals` and `hash` according to how they are in the post that I did link, not [345](https://piazza.com/class/k51bluky59n2jr?cid=345) since that has not been approved by the profs yet. As for the other methods, I figured we could add them as we wanted, as they do not have to be explicitly in the spec.

+1 for changing string.h to match [this](https://piazza.com/class/k51bluky59n2jr?cid=166) post, just for what's already in the spec (unless I have misunderstood)

**Comment by spencerlachance** [comment]
I think new methods have to be added to the spec as well. From the Piazza [FAQ](https://piazza.com/class/k51bluky59n2jr?cid=317):

> Q: What if the provided API is not sufficient? A: Ask for changes via git issues or pull requests. This can be additional methods, additional classes, different types.

Also, I don't think the professors have to approve a spec before we use it. Prof. Vitek has already acknowledged that the utility classes he provided wouldn't be the best going forward because they cache the hash code.

**Comment by Nomenokes** [comment]
Alright so I changed string and object to try and make them compatible, but I kept the old string::compare_to since that is the more common name

**Comment by Nomenokes** [comment]
Leaving this open till the other spec you linked is more solidified

**Comment by spencerlachance** [comment]
You know what, it seems like most people in the class want to use the professor's string and object classes so I change my vote to agree with @carloa21  and use those instead of the ones from the repository.

They're pretty similar anyway. Vitek's String class just has 2 more methods I think.

**Comment by drakstik** [comment]
> You know what, it seems like most people in the class want to use the professor's string and object classes so I change my vote to agree with @carloa21  and use those instead of the ones from the repository.
> They're pretty similar anyway. Vitek's String class just has 2 more methods I think.

Agreed, let's use Jan's implementations please.

**Comment by 0816seung** [comment]
In object.h line 8, the equals method requests a const Object* other as an argument.
Can this be changed this to Object* other?

**Comment by Nomenokes** [comment]
Sorry for late response. Added Vitek's specs to existing ones. 

@0816seung I am going to leave the const to fit with https://github.com/chasebish/cwc_object_string.git

You shouldn't need to change any implementation to make const work
