### ISSUE TITLE
Changing of Spec according to Piazza

### ISSUE THREAD

**Issue by carloa21** [Nomenokes/cs4500as01#4]
This [Piazza](https://piazza.com/class/k51bluky59n2jr?cid=331) post hints pretty hard that the Assignment 2 spec will want intArray, floatArray, etc instead of, for instance, wrapper classes around primitive int and float. For an idea to extend the spec, consider that Jan would like something like this to work:

ia.push_back( 42 );
int r = ia.get( 0 );

Thanks,
Carlo

**Comment by Nomenokes** [comment]
TBH I do not know how it's possible to implement this without janky casting. What API changes would make it easiest for you to implement? (I personally think it would be easiest to stick with wrappers because the assignment is so vague)

This goes to all the teams

**Comment by spencerlachance** [comment]
Can you do wrappers without janky casting? I'm getting these compiler errors: 

![image](https://user-images.githubusercontent.com/33330893/73328177-c6387280-4226-11ea-889c-9e194b27656c.png)

**Comment by Nomenokes** [comment]
oh whoops, that's just a typo in the tests (gotta use Object pointers)

Wrappers works fine without casting, if you wanted to support primitives without wrappers, it would be jank

**Comment by spencerlachance** [comment]
Why would it be jank? You'd just have an IntArray that takes in ints, a FloatArray that takes in floats, etc.

**Comment by Nomenokes** [comment]
I can add those if you want to implement it like that

**Comment by spencerlachance** [comment]
Yeah sure, let's do it. Thanks!

**Comment by 0816seung** [comment]
Seeing as the spec for IntArray, FloatArray, etc. hasn't been posted as of right now and we've begun work on the array implementation, we are moving forward with wrappers around the primitives.

**Comment by Nomenokes** [comment]
Added arrays for primitives with only the most necessary methods. Will start making tests. Let me know if you want any changes

**Comment by Nomenokes** [comment]
Added tests
