### ISSUE TITLE
Compiler errors in test-array.cpp

### ISSUE THREAD

**Issue by spencerlachance** [Nomenokes/cs4500as01#6]
- On lines 91 and 94, there are too many arguments being passed to `check`
- On line 113, it says `removeRange` instead of `remove_range`
- On lines 127, 130, and 131, there are missing parentheses

Would you mind fixing these?

**Comment by Nomenokes** [comment]
I think I got all of them, lmk if there are any more

**Comment by spencerlachance** [comment]
/home/slachance25/projects/cs4500/a2part1/test-array.cpp: In function ‘void testAdd()’:
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:58:50: error: expected ‘)’ before ‘;’ token
     check("insertall 4", arr2->get(4)->equals(hi);
                                                  ^
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:60:50: error: expected ‘)’ before ‘;’ token
     check("insertall 6", arr2->get(6)->equals(hi);
                                                  ^
/home/slachance25/projects/cs4500/a2part1/test-array.cpp: In function ‘void testRemove()’:
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:117:50: error: invalid conversion from ‘Object*’ to ‘String*’ [-fpermissive]
     check("set replace return", (free1 = arr->set(new String("foo"), 0))->equals(hi));
                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:120:58: error: no matching function for call to ‘Array::set(String*)’
     check("set at size return", arr->set(new String("hi")) == NULL, 1);
                                                          ^
In file included from /home/slachance25/projects/cs4500/a2part1/test-array.cpp:3:0:
/home/slachance25/projects/cs4500/a2part1/array.h:114:17: note: candidate: Object* Array::set(Object*, size_t)
         Object* set(Object* val, size_t index) {
                 ^~~
/home/slachance25/projects/cs4500/a2part1/array.h:114:17: note:   candidate expects 2 arguments, 1 provided
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:124:48: error: invalid conversion from ‘Object*’ to ‘String*’ [-fpermissive]
     check("remove return", (free2 = arr->remove(0))->equals(foo));
                                     ~~~~~~~~~~~^~~
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:125:48: error: invalid conversion from ‘Object*’ to ‘String*’ [-fpermissive]
     check("remove shrink", (free3 = arr->remove(0))->equals(hi));
                                     ~~~~~~~~~~~^~~
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:130:49: error: invalid conversion from ‘Object*’ to ‘String*’ [-fpermissive]
     check("remove index 1", (free4 = arr->remove(1))->equals(hi));
                                      ~~~~~~~~~~~^~~
/home/slachance25/projects/cs4500/a2part1/test-array.cpp: In function ‘void testQueries()’:
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:172:52: error: expected ‘)’ before ‘;’ token
     check("cleared arrays equal", arr->equals(arr2);
                                                    ^
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:175:54: error: expected ‘)’ before ‘;’ token
     check("non-empty arrays equal", arr2->equals(arr);
                                                      ^
/home/slachance25/projects/cs4500/a2part1/test-array.cpp:176:50: error: expected ‘)’ before ‘;’ token
     check("symmetric equality", arr->equals(arr2);

**Comment by spencerlachance** [comment]
58, 60, 172, 175, and 176 missing parentheses

**Comment by Nomenokes** [comment]
Fixed
"i tHinK i Got aLl of tHEm"

**Comment by spencerlachance** [comment]
2 more:

- Please move the `1` argument of the `set at size return` test inside the `set` function call
- `index of non-null` should be checking for index 2 I believe

**Comment by Nomenokes** [comment]
fixed

**Comment by spencerlachance** [comment]
Shouldn't `arr3` in the insert tests be `[bat, bar, hi, NULL, baz, end]`? Unless I misunderstood your insert spec.

**Comment by Nomenokes** [comment]
Yes, not sure why I did that order to start with. Updated

**Comment by Nomenokes** [comment]
Added tests for primitive arrays

**Comment by spencerlachance** [comment]
FINAL TEST CORRECTIONS:

- Line 218 `BA get 2` should be true
- Line 230 `append FA changes size` should be 3
- Please cast all values that you're checking against a float with `==` to float. The tests are failing even though our Array has the correct values in it.
- Line 294-295 `IA indexof` and `IA remove RV` - the index should be 1
- Line 300-301 `FA indexof` and `FA remove RV` - the index should be 3

Let me know if I misunderstood your tests, but I think these are typos.

**Comment by Nomenokes** [comment]
Fixed

**Comment by spencerlachance** [comment]
Should line 275 be `check("FA set RV", fa->set(5.5, 1) == 1.1f);`?

**Comment by Nomenokes** [comment]
Yes, fixed

**Comment by spencerlachance** [comment]
You forgot the f in 1.1f

**Comment by Nomenokes** [comment]
dangit, fixed
