### ISSUE TITLE
Add equals method to Array spec

### ISSUE THREAD

**Issue by spencerlachance** [Nomenokes/cs4500as01#7]
I want to override this method instead of using Object's version. Could you add it to Array?

Thanks!

**Comment by Nomenokes** [comment]
I'm pretty sure you are free to do that without it being explicitly in the API because it's in Object

**Comment by Nomenokes** [comment]
Yeah since they are being so vague I'm going to go ahead and say you can implement equals because of inheritance and you can blame me if that is not legal for some reason

I'm going the leave the specs the same to leave it open-ended
